project:
  type: book
  output-dir: docs

book:
  title: "Stellar Physics"
  author:
    - name: Dr Rosaria Lena
      email: rosaria.lena@glasgow.ac.uk
      affiliation:
        - name: School of Physics and Astronomy, University of Glasgow
          # address: Kelvin Building room 620
      # email: rosaria.lena@glasgow.ac.uk
  
  date: "2024"
  chapters:
    - index.qmd
    - intro.qmd
    - SP1.1_-_Stellar_Properties.qmd
    - SP1.2_-_Stellar_classification.qmd
    - SP1.3_-_Variables_and_Binaries.qmd
    - SP1.4_-_Stellar_Atmospheres.qmd
    - SP1.5_-_Stellar_Models.qmd
    - SP1.6_-_Post-Main-Sequence.qmd
    - SP2.1_-_Supernovae.qmd
    - SP2.2_-_Degenerate_Matter.qmd
    - SP2.3_-_White_Dwarfs.qmd
    - SP2.4_-_Neutron_Stars.qmd
    - SP2.5_-_Black_Holes.qmd
    # - summary.qmd
    - references.qmd

  search: 
    location: sidebar
    type: overlay

  downloads: [pdf, epub]
  sidebar:
    pinned: true
    # tools:
    #   - icon: save
    #     menu:
    #       - text: ""
    #         url:  "#"
    #       - text: ""
    #         url:  "#"
    #       - text: ""
    #         url:  "#"

  
  
bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    number-sections: true
    # embed-resources: true
    code-fold: true
    code-tools:
      source: false
    code-summary: Show the code
    code-line-numbers: true
    execute:
      echo: true
  pdf:
    pdf-engine: xelatex
    include-in-header:
      - "header.tex"
 #   #pandoc_args: ["--extract-media","."]
    documentclass: scrreprt
    toc: true
    toc-depth: 3
    date: last-modified
    number-sections: true
    colorlinks: true
    cite-method: biblatex



